services:
  flask_gunicorn_web:
    container_name: flask_gunicorn_web
    depends_on:
      - caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      - GUNICORN_CMD_ARGS="--workers 4 --bind 0.0.0.0:5000"
    user: mst
    networks:
      - caddy

  portainer:
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    depends_on:
      - caddy
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - caddy 

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - WEB_DOMAIN=mstservices.ddns.net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - caddy

# Add networks section outside services
networks:
  caddy:
    driver: bridge
